### ISSUE TITLE
Support for publicRuntimeConfig

### ISSUE THREAD

**Issue by danielroe** [nuxt-community/nuxt-logrocket#155]
Would be nice to support `$config` for `LOGROCKET_ID`, etc.

* Details: https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-runtime-config/
* See for example the way `@nuxtjs/axios` has implemented it: https://github.com/nuxt-community/axios-module/blob/master/lib/plugin.js#L192-L198

**Comment by farzadso** [comment]
@danielroe Good point. Do you think you could open a PR for the support?
