### ISSUE TITLE
enable/disable logrocket

### ISSUE THREAD

**Issue by miteyema** [nuxt-community/nuxt-logrocket#28]
At the moment, logrocket is only disabled when you are in dev mode.
It would be nice to able to set your own logic whether or not to enable logrocket.

Use case: I build a deploy preview on my server (that is: production mode), I want to test that specific deploy without logrocket recording it.

**Comment by farzadso** [comment]
Why don't you just clear `logRocketId` in your `nuxt.config.js` file for that specific deploy?

**Comment by miteyema** [comment]
Ok, never thought of that, thanks!
FYI: an error is thrown in the console log if `logRocketId: ''` which makes sense

**Comment by farzadso** [comment]
@miteyema Thanks for the tip.

This should be fixed in [v1.2.5](https://github.com/nuxt-community/nuxt-logrocket/releases/tag/v1.2.5)

Can you please test and confirm? I'd appreciate it.

**Comment by miteyema** [comment]
Awesome, thanks for the fix!

**Comment by adarsh4d** [comment]
@farzadso Is there a way to enable/disable for certain users/our own logic, I would need to disable it for certain user types.
