### ISSUE TITLE
add support for controlling isProduction flag

### ISSUE THREAD

**Issue by NextStepGuru** [nuxt-community/nuxt-logrocket#60]
I run multiple environments on my application. Most of the environments I deploy & test I do not want logrocket running. 

Can you add a new option to control when `isProduction` flag is `true` where I could control this via `nuxt.config.js`?

**Comment by farzadso** [comment]
Hi,

This module only runs on production environments (`NODE_ENV=production`).

You can control logrocket not running in your deploy and test environments by using a different value for `NODE_ENV`.
