### ISSUE TITLE
add support for LogRocket URL in Sentry

### ISSUE THREAD

**Issue by NextStepGuru** [nuxt-community/nuxt-logrocket#61]
Can you add support for detecting `@nuxtjs/sentry` and automatically add the LogRocket URL to sentry?

Here is the docs on how to get & add the url https://docs.logrocket.com/docs/sentry

`this.$sentry` is the sentry variable to append the url.

**Comment by farzadso** [comment]
@NextStepGuru Thanks for opening this issue and sorry for addressing it so late.

This feature has been added and can be used starting from [`v1.4.0`](https://github.com/nuxt-community/nuxt-logrocket/releases/tag/v1.4.0).
