### ISSUE TITLE
Add additional options (textSanitizer)

### ISSUE THREAD

**Issue by jrah** [nuxt-community/nuxt-logrocket#63]
It appears that the only options available are the logrocket id and development mode.  However, it could really benefit from being able to use `textSanitizer`:

https://docs.logrocket.com/reference#dom

I am hoping you will tell me I am wrong and I am just missing something obviously.

**Comment by malkhuzayyim** [comment]
Seeing as this doesn't expose the init options originally available by the init method: https://docs.logrocket.com/reference#init

Kind of makes the module very limiting.

Would make more sense if the entire init options was exposed in nuxt.config.js module options

As things stand currently, kind of makes more sense to just grab the native logrocket package and register it in a normal nuxt plugin. Unless I'm missing something.

**Comment by farzadso** [comment]
Thanks for pointing this out @jrah and @malkhuzayyim and sorry for the late response.

All of the configuration options have been added to this module and can be tested as of [`v1.5.0`](https://github.com/nuxt-community/nuxt-logrocket/releases/tag/v1.5.0).

You can find the docs here: https://github.com/nuxt-community/nuxt-logrocket#options
