### ISSUE TITLE
How can I fix the ‘Payload too large (> 10MB). Event: lr.browser.NodeInitEvent’ warning.

### ISSUE THREAD

**Issue by s-tanoue** [nuxt-community/nuxt-logrocket#81]
Hello everyone.

I'm using LogRocket and this plugin in my project now.
But I can't not see the video.
[![Image from Gyazo](https://i.gyazo.com/44b7e5683c83c8bb3b81611182327476.jpg)](https://gyazo.com/44b7e5683c83c8bb3b81611182327476)

I believe the cause of this is the ‘Payload too large (> 10MB). Event: lr.browser.NodeInitEvent’ warning on the console.

Do you have any tips on how to fix it?

**Comment by lucasbaze** [comment]
I'm unfortunately experiencing the exact same issue. While this is not a solution in my opinion, just to get it to continue to record requests I set the `dom` property on LogRocket.init to false like: 

```
LogRocket.init('APP_ID', {
    dom: {
        isEnabled: false
    }
}
```

If you've found a way to track what is actually getting sent, please share!

**Comment by unoscar** [comment]
Hi. Has there been any fix for this item?

**Comment by farzadso** [comment]
I'm using the same module in various projects and not running into this issue.

Can anyone create a code sandbox of some sort?

**Comment by EricKit** [comment]
I have this message as well, but it's with NextJS if that helps. And it only happens in dev mode.

**Comment by farzadso** [comment]
@EricKit Can you help me reproduce the issue?

**Comment by lucasbaze** [comment]
As an update, my issue was related to our webpack plugin injecting styles per file, so on initial load, the dom was changing rapidly as the styles were injected and caused the payload to be too large for the first couple of seconds, which LogRocket then subsequently cuts off sending info. Sorry I don't have a repro.

**Comment by pabloromStrivelabs** [comment]
@lucasbaze Could you provide your solution so that on the initial load it didn't cause the payload to be too large?
